mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 10.15.52.44 #localhost or 10.15.52.44
    port: 1883
    keepalive: 60
  private_path: device/001
  serializer: json:dumps
  deserializer: json:loads

serializer: json:dumps
deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong

  # fixture P0
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Fixture
    topic_from: JFMX/L1/sharework/station/p0
    topic_to: /JFMX/L1/sharework/station/p0
  # fixture P1
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Fixture
    topic_from: JFMX/L1/sharework/station/p1
    topic_to: /JFMX/L1/sharework/station/p1
  # fixture P2
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Fixture
    topic_from: JFMX/L1/sharework/station/p2
    topic_to: /JFMX/L1/sharework/station/p2
  # fixture P3
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Fixture
    topic_from: JFMX/L1/sharework/station/p3
    topic_to: /JFMX/L1/sharework/station/p3

  # storage 0
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Storage
    topic_from: JFMX/L1/sharework/station/load/storage0
    topic_to: /JFMX/L1/sharework/station/load/storage0

  # storage 1
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Storage
    topic_from: JFMX/L1/sharework/station/load/storage1
    topic_to: /JFMX/L1/sharework/station/load/storage1

  # storage 2
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Storage
    topic_from: JFMX/L1/sharework/station/load/storage2
    topic_to: /JFMX/L1/sharework/station/load/storage2


  # operator feedback
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:OperatorState
    topic_from: JFMX/L1/sharework/station/operator
    topic_to: /JFMX/L1/sharework/station/operator


  # storage unload
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: mqtt_scene_integration.msg:Storage
    topic_from: JFMX/L1/sharework/station/unload/storage0
    topic_to: /JFMX/L1/sharework/station/unload/storage0

  # robot status
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: mqtt_scene_integration.msg:RobotState
    topic_from: /JFMX/L1/sharework/robot/status
    topic_to: JFMX/L1/sharework/robot/status

  # operator status
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: mqtt_scene_integration.msg:OperatorState
    topic_from: /JFMX/L1/sharework/robot/operator
    topic_to: JFMX/L1/sharework/robot/operator
